#Number of initial web servers
servers=10

# minimim number of servers
min_servers=2

#simulation clock cycles
cycles=10000

# If queue < min_queue * servers -> remove a server
# If queue > max_queue * servers -> add a server
min_queue=50
max_queue=80

#minimum scale wait time
scale_wait=100

#new random requests every N clock cycles
new_req_interval=10

#route by job type (0=no, 1=yes)
use_switch=0

#log file
log_file=simulation.log

#ip_block
block_ip= 10.0.
block_ip=192.168.

