# Number of initial web servers
servers=10

# Total simulation clock cycles
cycles=10000

# If queue < min_queue * servers -> remove a server
# If queue > max_queue * servers -> add a server
min_queue=50
max_queue=80

#minimum scale wait time
scale_wait=100

# Inject new random requests every N clock cycles
new_req_interval=10

# Use Switch to route by job type (0=no, 1=yes)
use_switch=0

# Output log file
log_file=simulation.log

